# Generated by Django 4.2.7 on 2025-07-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
