# Generated by Django 4.2.7 on 2025-07-07 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.slug_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('resource_type', models.CharField(choices=[('event', 'Events'), ('info_system', 'Information Systems/Websites'), ('map', 'Maps'), ('media', 'Media'), ('news', 'News'), ('policy', 'Policies'), ('project', 'Projects'), ('publication', 'Publications'), ('technology', 'Technologies'), ('training', 'Training/Seminars'), ('webinar', 'Webinars'), ('product', 'Products')], max_length=50)),
                ('keywords', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('commodities', models.ManyToManyField(blank=True, db_table='tbl_knowledge_resources_metadata_commodities', max_length=100, to='appAdmin.commodity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_created', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, db_table='tbl_knowledge_resources_metadata_tags', max_length=100, to='appAdmin.tag')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgeresources',
            name='machine_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('date', models.DateTimeField()),
                ('speaker', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('documentation_link', models.URLField(blank=True)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='knowledge_resources/webinars/')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_webinar',
            },
        ),
        migrations.CreateModel(
            name='TrainingSeminar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('speakers', models.TextField(blank=True)),
                ('total_participants', models.IntegerField(blank=True, null=True)),
                ('documentation_link', models.URLField(blank=True)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='knowledge_resources/training/')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_seminar', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_training_seminar',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('technologies', models.CharField(max_length=255)),
                ('products', models.CharField(max_length=255)),
                ('adoption_status', models.CharField(choices=[('adopted', 'Adopted'), ('for_incubation', 'For Incubation')], max_length=50)),
                ('year_introduced', models.IntegerField()),
                ('ip_asset', models.CharField(blank=True, max_length=255)),
                ('brief_description', models.TextField()),
                ('support_facilities', models.TextField(blank=True)),
                ('available_experts', models.TextField(blank=True)),
                ('experts_email', models.EmailField(blank=True, max_length=254)),
                ('experts_phone', models.CharField(blank=True, max_length=20)),
                ('funding_source', models.CharField(blank=True, choices=[('pcaarrd', 'PCAARRD-funded'), ('dost', 'DOST-funded'), ('suc', 'SUC-funded'), ('other', 'Other')], max_length=50)),
                ('technologies_offered_for', models.CharField(blank=True, max_length=255)),
                ('technology_transfer_pathway', models.TextField(blank=True)),
                ('google_link_photos', models.URLField(blank=True)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='knowledge_resources/technologies/')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='appAdmin.commodity')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_technology',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_resources/publications/')),
                ('date_published', models.DateField()),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book'), ('report', 'Technical Report'), ('thesis', 'Thesis/Dissertation'), ('other', 'Other')], default='other', max_length=100)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_publication',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('program_title', models.CharField(blank=True, max_length=255)),
                ('project_title', models.CharField(max_length=255)),
                ('project_leader', models.CharField(max_length=255)),
                ('source_of_fund', models.CharField(blank=True, max_length=255)),
                ('cooperating_agency', models.CharField(blank=True, max_length=255)),
                ('collaborating_agency', models.CharField(blank=True, max_length=255)),
                ('implementing_agency', models.CharField(blank=True, max_length=255)),
                ('total_approved_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('implementing_agency_counterpart', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('extension_months', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('terminated', 'Terminated')], max_length=50)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_project',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('products', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_info', models.TextField(blank=True)),
                ('documentation_link', models.URLField(blank=True)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='knowledge_resources/products/')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_product',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('policy_type', models.CharField(choices=[('research', 'Policy Research'), ('formulated', 'Policy Formulated')], max_length=50)),
                ('agency', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('advocacy_project', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('findings', models.TextField(blank=True)),
                ('policy', models.TextField(blank=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_policy',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('headline', models.CharField(help_text='News headline/title', max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, help_text="Author's position/title", max_length=255)),
                ('content', models.TextField()),
                ('source', models.URLField(blank=True, help_text='Source URL of the news')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='knowledge_resources/news_images/')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='appAdmin.resourcemetadata')),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'tbl_knowledge_resources_news',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_media',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('map_file', models.FileField(upload_to='maps/')),
                ('map_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_map',
            },
        ),
        migrations.CreateModel(
            name='InformationSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
                ('organization_owner', models.CharField(max_length=255)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('brief_explanation', models.TextField()),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information_system', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_information_system',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('documentation_link', models.URLField(blank=True)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='knowledge_resources/events/')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_event',
            },
        ),
    ]
